"""add attacks table

Revision ID: 1513e3c037de
Revises: e14e312e1359
Create Date: 2026-08-22 16:45:31.520967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1513e3c037de'
down_revision: Union[str, Sequence[str], None] = 'e14e312e1359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attack_type', sa.Enum('PORT_SCAN', 'BRUTE_FORCE', 'DOS', 'MALWARE', 'PHISHING', name='attacktype'), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=False),
    sa.Column('target_asset_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SIMULATED', 'DETECTED', 'BLOCKED', name='attackstatus'), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attacks_id'), 'attacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attacks_id'), table_name='attacks')
    op.drop_table('attacks')
    # ### end Alembic commands ###
