"""Add subnet relationship to assets

Revision ID: e14e312e1359
Revises: d2eaad7a4a7c
Create Date: 2026-07-27 16:02:00.687766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e14e312e1359'
down_revision: Union[str, Sequence[str], None] = 'd2eaad7a4a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('subnet_id', sa.Integer(), nullable=True))
    op.alter_column('assets', 'status',
               existing_type=postgresql.ENUM('Active', 'Inactive', 'Maintenance', 'Compromised', name='assetstatus'),
               nullable=False)
    op.create_foreign_key(None, 'assets', 'subnets', ['subnet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.alter_column('assets', 'status',
               existing_type=postgresql.ENUM('Active', 'Inactive', 'Maintenance', 'Compromised', name='assetstatus'),
               nullable=True)
    op.drop_column('assets', 'subnet_id')
    # ### end Alembic commands ###
